### ISSUE TITLE
Clang 3.6 instead of clang 3.4

### ISSUE THREAD

**Issue by cibersheep** [emscripten-core/emscripten-fastcomp-clang#12]
Hi!
I'm trying to compile em-Dosbox (but it happens the same with any other transcompile I try after updating emscripten).

emcc -v shows:
`emcc (Emscripten GCC-like replacement + linker emulating GNU ld ) 1.22.1`
`clang version 3.9.0 (https://github.com/kripken/emscripten-fastcomp-clang/ 271ce598c3d1fe74efadc254f5be1b57edea9f41) (https://github.com/kripken/emscripten-fastcomp/ 61acfb230665464544f2e8db292f8999fc3c628c) (emscripten 1.36.0 : 1.36.0)`
`Target: x86_64-unknown-linux-gnu`
`Thread model: posix`
`InstalledDir: MyDirectory/emsdk_portable/clang/fastcomp/build_master_64/bin`
`Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/5.4.0`
`Found candidate GCC installation: /usr/lib/gcc/i686-linux-gnu/6.0.0`
`Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9`
`Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.3`
`Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0`
`Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.0.0`
`Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.4.0`
`Candidate multilib: .;@m64`
`Selected multilib: .;@m64`
`WARNING  root: LLVM version appears incorrect (seeing "(https://github.com/kripken/emscripten-fastcomp-clang/", expected "3.4")`
`INFO     root: (Emscripten: Running sanity checks)`

When I try to compile, this error:
`/usr/share/emscripten/em++  -O3  -s TOTAL_MEMORY=67108864 --pre-js pre.js  -o dosbox.html dosbox.o  cpu/libcpu.a debug/libdebug.a dos/libdos.a fpu/libfpu.a  hardware/libhardware.a gui/libgui.a ints/libints.a misc/libmisc.a shell/libshell.a hardware/serialport/libserial.a libs/gui_tk/libgui_tk.a `
`Exception in thread Thread-3:`
`Traceback (most recent call last):`
`  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python2.7/threading.py", line 754, in run`
`    self.__target(*self.__args, **self.__kwargs)`
`  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results`
`    task = get()`
`TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())`

What am I doing wrong?

**Comment by kripken** [comment]
I think your repos are out of sync. The 3 repos (emscripten, fastcomp, fastcomp-clang) must all be on the same version number or the same up to date branch, http://kripken.github.io/emscripten-site/docs/building_from_source/building_fastcomp_manually_from_source.html?highlight=repos#branches

Or, if you are using the emsdk, perhaps it needs to be updated?

**Comment by juj** [comment]
Emsdk automatically takes all the three repos in sync, there's no special update steps there to synchronize them.

**Comment by cibersheep** [comment]
I forgot to mention: I use Ubuntu 16.04 64bits.
I didn't build Emscripten, [I've download it](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) and [updated emsdk as it says](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html#updating-the-sdk).

After updating, I got the error and the version mismatch.

The result of `./emsdk list` is

The following precompiled tool packages are available for download:
           node-4.1.1-32bit         
    (*)    node-4.1.1-64bit         	INSTALLED
           emscripten-1.30.0        
           emscripten-1.34.1        
           emscripten-1.35.0        

The following tools can be compiled from source:
           clang-tag-e1.36.13-32bit 
           clang-tag-e1.36.14-32bit 
           clang-tag-e1.36.13-64bit 
           clang-tag-e1.36.14-64bit 
           clang-incoming-32bit     
           clang-incoming-64bit     
           clang-master-32bit       
    (*)    clang-master-64bit       	INSTALLED
           emscripten-tag-1.36.13-32bit
           emscripten-tag-1.36.14-32bit
           emscripten-tag-1.36.13-64bit
           emscripten-tag-1.36.14-64bit
           emscripten-incoming-32bit
           emscripten-master-32bit  
           emscripten-incoming-64bit
    (*)    emscripten-master-64bit  	INSTALLED

The following precompiled SDKs are available for download:

The following SDKs can be compiled from source:
         sdk-incoming-32bit       
         sdk-incoming-64bit       
         sdk-master-32bit         
    *    sdk-master-64bit         	INSTALLED
         sdk-tag-1.36.13-32bit    
         sdk-tag-1.36.14-32bit

**Comment by cibersheep** [comment]
Ok. I remerbered also that with the last update I did all steps from instructuions and tried running emcc with python3. That worked.

Solved the error that stopped transpilation.
`python3 routeto/emcc routeto/files`
