### ISSUE TITLE
error:        use of undeclared identifier       '__builtin_ia32_readeflags_u32'   return __builtin_ia32_readeflags_u32();

### ISSUE THREAD

**Issue by fhk** [emscripten-core/emscripten-fastcomp-clang#29]
Hi just trying to compile [this ](https://github.com/ERGO-Code/HiGHS) project.

Currently I am using the following commands:

`cd ./HiGHS/src`
`em++ ./interfaces/highs_c_api.cpp -I . -s WASM=1 -o sol.js -std=c++11`

There are a number of errors shown in the full log below.

The main error is "undeclared identifier" for many of the ia32 '__builtin_ia32_readeflags_u32', '__builtin_ia32_writeeflags_u32',  '__builtin_ia32_rdpmc', ...

Do I need to set a flag? Is this expected?

> In file included from ./interfaces/highs_c_api.cpp:2:
In file included from ./Highs.h:19:
In file included from ./lp_data/HighsModelObject.h:14:
In file included from ./lp_data/HighsOptions.h:22:
In file included from ./presolve/Presolve.h:26:
In file included from ./simplex/HTimerPre.h:25:
In file included from /home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/x86intrin.h:27:
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/ia32intrin.h:48:10: error: 
      use of undeclared identifier
      '__builtin_ia32_readeflags_u32'
  return __builtin_ia32_readeflags_u32();
         ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/ia32intrin.h:54:3: error: 
      use of undeclared identifier
      '__builtin_ia32_writeeflags_u32'
  __builtin_ia32_writeeflags_u32(__f);
  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/ia32intrin.h:60:10: error: 
      use of undeclared identifier '__builtin_ia32_rdpmc'
  return __builtin_ia32_rdpmc(__A);
         ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/ia32intrin.h:66:10: error: 
      use of undeclared identifier '__builtin_ia32_rdtscp'
  return __builtin_ia32_rdtscp(__A);
         ^
In file included from ./interfaces/highs_c_api.cpp:2:
In file included from ./Highs.h:19:
In file included from ./lp_data/HighsModelObject.h:14:
In file included from ./lp_data/HighsOptions.h:22:
In file included from ./presolve/Presolve.h:26:
In file included from ./simplex/HTimerPre.h:25:
In file included from /home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/x86intrin.h:29:
In file included from /home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/immintrin.h:28:
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:47:5: error: 
      use of undeclared identifier '__builtin_ia32_emms'; did you
      mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:47:5: note: 
      '__builtin_isless' declared here
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:47:25: error: 
      too few arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:64:19: error: 
      use of undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:81:12: error: 
      use of undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
           ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:143:19: error: 
      use of undeclared identifier '__builtin_ia32_packsswb'
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:173:19: error: 
      use of undeclared identifier '__builtin_ia32_packssdw'
    return (__m64)__builtin_ia32_packssdw((__v2si)__m1, (...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:203:19: error: 
      use of undeclared identifier '__builtin_ia32_packuswb'
    return (__m64)__builtin_ia32_packuswb((__v4hi)__m1, (...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:230:19: error: 
      use of undeclared identifier '__builtin_ia32_punpckhbw'
    return (__m64)__builtin_ia32_punpckhbw((__v8qi)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:253:19: error: 
      use of undeclared identifier '__builtin_ia32_punpckhwd'
    return (__m64)__builtin_ia32_punpckhwd((__v4hi)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:274:19: error: 
      use of undeclared identifier '__builtin_ia32_punpckhdq'
    return (__m64)__builtin_ia32_punpckhdq((__v2si)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:301:19: error: 
      use of undeclared identifier '__builtin_ia32_punpcklbw'
    return (__m64)__builtin_ia32_punpcklbw((__v8qi)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:324:19: error: 
      use of undeclared identifier '__builtin_ia32_punpcklwd'
    return (__m64)__builtin_ia32_punpcklwd((__v4hi)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:345:19: error: 
      use of undeclared identifier '__builtin_ia32_punpckldq'
    return (__m64)__builtin_ia32_punpckldq((__v2si)__m1, ...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:366:19: error: 
      use of undeclared identifier '__builtin_ia32_paddb'
    return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v...
                  ^
/home/banana/Documents/code/emsdk/clang/fastcomp/build_incoming_64/lib/clang/6.0.1/include/mmintrin.h:387:19: error: 
      use of undeclared identifier '__builtin_ia32_paddw'
    return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v...
                  ^
fatal error: too many errors emitted, stopping now
      [-ferror-limit=]
20 errors generated.
shared:ERROR: compiler frontend failed to generate LLVM bitcode, halting

**Comment by dschuff** [comment]
It looks like the problem is in https://github.com/ERGO-Code/HiGHS/blob/master/src/simplex/HTimerPre.h#L22
where the code assumes that it is running on x86, and it tries to use all the x86-specific SIMD intrinsics (hence the "_ia32_" in their names).  Wasm is not x86 and does not directly support those x86 intrinsics. Your best bet right now is to try to see if there are plain C/C++ implementations of the functionality you need. You could also try porting that code to use wasm simd (https://emscripten.org/docs/porting/simd.html) although that extension hasn't shipped in browsers yet.

**Comment by fhk** [comment]
Great thanks
